### ISSUE TITLE
加载扩展程序时出错

### ISSUE THREAD

**Issue by msterdb** [ZDL-Git/browse-manager#1]
无法加载以下来源的扩展程序： C:\Users\user11\Desktop\browse-manager-3.0.5.zip. Could not unzip extension for install.

windows10
chrome版本 74.0.3729.131（正式版本） （32 位）

**Comment by ZDL-Git** [comment]
你好，安装前请先手动解压好文件，再将文件夹拖入插件安装界面即可，请多看几遍gif的安装说明。

**Comment by ZDL-Git** [comment]
现在已经提供了crx格式的安装文件，可按项目主页中的说明安装。
