### ISSUE TITLE
能否直接将不想看见的网站从搜索里抹去？

### ISSUE THREAD

**Issue by beitangyao** [ZDL-Git/browse-manager#11]
如题，我是一个平时爱折腾电脑的高中生。平日里没少下载自己喜欢的软件啊什么的。
但是网络上一些网站是真滴恶心，直接在网站前面十几条占着。
比如华军软件园啊，绿色下载站啊，下载吧什么的，还是最好直接弄掉好（p2p下载器真的太恶心了），官网都看不到了。

**Comment by ZDL-Git** [comment]
看一下 [uBlacklist](https://chrome.google.com/webstore/detail/ublacklist/pncfbmialoiaghdehhbnbhkkgmjanfhe/related)
