### ISSUE TITLE
prefix不起作用

### ISSUE THREAD

**Issue by l2tpv3** [ZDL-Git/browse-manager#16]
百度文库的文档url打开后会自行添加时间戳，插件中搜索文档id并加入prefix，刷新后还是不能关闭页面

**Comment by ZDL-Git** [comment]
prefix 名单，是前缀名单，不是通配符名单。
使用方法举例：
url：

> https://wenku.baidu.com/view/33787541240c844769eaeeb5.html?fr=hp_doclist&_wkts_=1712464336639

需要添加prefix：

> https://wenku.baidu.com/view/33787541240c844769eaeeb5.html

**Comment by ZDL-Git** [comment]
> 百度文库的文档url打开后会自行添加时间戳，插件中搜索文档id并加入prefix，刷新后还是不能关闭页面

请看这个说明：
https://github.com/ZDL-Git/browse-manager/issues/7#issuecomment-2041334173
