### ISSUE TITLE
页面无法右键怎么添加名单【我想添加p.to进黑名单添加不了？】

### ISSUE THREAD

**Issue by ceh-ylhy** [ZDL-Git/browse-manager#4]
这是斐讯路由的后台，但是在进去网页不能鼠标右击添加，我哭了，开发者能不能加一个手动添加

**Comment by ZDL-Git** [comment]
试了下，可以唉，你再试试，然后详细描述一下
<img width="1280" alt="屏幕快照 2019-09-07 12 35 24" src="https://user-images.githubusercontent.com/30430217/64469857-0a3db480-d16c-11e9-92ef-c59138b6ed05.png">

**Comment by ZDL-Git** [comment]
是中病毒了？

**Comment by ZDL-Git** [comment]
大概知道你说的：页面禁止了右键功能。这个后边可以考虑增加手动添加名单的功能

**Comment by ZDL-Git** [comment]
解决方法：右键扩展图标，如图，即使页面禁止了右键，也可以在这使用扩展的菜单。
<img width="1280" alt="屏幕快照 2019-09-07 14 50 40" src="https://user-images.githubusercontent.com/30430217/64471076-18490080-d17f-11e9-8ce5-f283d1641e64.png">
