### ISSUE TITLE
feature wanted:手动编辑名单

### ISSUE THREAD

**Issue by jsonlog** [ZDL-Git/browse-manager#6]
问题:有的网址会经过几次快速中转调到目标网址,只想屏蔽中转网址,但比较难人工捕捉,又不想屏蔽目标网址

例子:比如xxx.com会中转到s.click.taobao.com再调到taobao,总不能把淘宝禁了

解决:希望可以提供手动增加名单的功能,现在只能删不能加

**Comment by ZDL-Git** [comment]
中间地址拉黑后标签会自动关闭

**Comment by jsonlog** [comment]
就是没办法添加中间地址并拉黑(难以手动捕获)
就是要这个关闭标签的效果,因为平常我不需要中转就可以访问目标地址

比如:平常我在浏览器输入taobao.com就可以访问淘宝了,官网并不会先跳到s.click.taobao.com再跳到taobao.com,所以屏蔽s.click.taobao.com不影响我日常使用taobao.com  

而我不小心进入垃圾站点会**自动**(很难手动捕获)多次中转到s.click.taobao.com(很难手动捕获)再跳到taobao.com

**Comment by ZDL-Git** [comment]
可以，下个版本

**Comment by ZDL-Git** [comment]
临时可以在扩展背景页console中使用以下命令添加：
LS.setItem("https://www.baidu.com", OPERATIONS.addDomainBlacklist);

**Comment by ZDL-Git** [comment]
已发布。
